RegisterServerEvent("deathmessages:broadcastDeath")
RegisterServerEvent("deathmessages:broadcastMurder")
AddEventHandler("deathmessages:broadcastDeath", function(victimID)
	print("Someone died")
	TriggerClientEvent("deathmessages:notifyDeath",source, victimID)
end)

AddEventHandler("deathmessages:broadcastMurder", function(victimID, killerID, weapon, killerInVehicle, killerType)
	TriggerClientEvent("deathmessages:notifyMurder",source, victimID, killerID, weapon, killerInVehicle, killerType)
end)